// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBefoeQxTw8w5p8Z0Mvh102FEq0JeHLOo8',
    appId: '1:101683233028:web:c7dd4ab07d92914fa61051',
    messagingSenderId: '101683233028',
    projectId: 'cookants-bd',
    authDomain: 'cookants-bd.firebaseapp.com',
    storageBucket: 'cookants-bd.firebasestorage.app',
    measurementId: 'G-NR6T3LWC6K',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaji0PIzAl2lVzyFEiTanbEv3ubd9nLRY',
    appId: '1:101683233028:ios:58010a6ad8b8fcfca61051',
    messagingSenderId: '101683233028',
    projectId: 'cookants-bd',
    storageBucket: 'cookants-bd.firebasestorage.app',
    iosBundleId: 'com.example.cookants',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOts5Xp7xC0CAnFcOGl3MXBo2B-4zTuUc',
    appId: '1:101683233028:android:f36d2926d371d081a61051',
    messagingSenderId: '101683233028',
    projectId: 'cookants-bd',
    storageBucket: 'cookants-bd.firebasestorage.app',
  );

}